version: "3.9"

services:
  api:
    image: claimsight-ai-api:latest
    build:
      context: .
      dockerfile: claimsight_ai/api/Dockerfile
    command: >
      uvicorn claimsight_ai.api.main:app
      --host 0.0.0.0 --port 8000
      --log-level info
      --proxy-headers
    ports:
      - "8000:8000"
    volumes:
      - .:/workspace
    working_dir: /workspace
    env_file: .env
    environment:
      SNOWFLAKE_USER:       "${SNOWFLAKE_USER:-}"
      SNOWFLAKE_PASSWORD:   "${SNOWFLAKE_PASSWORD:-}"
      SNOWFLAKE_ACCOUNT:    "${SNOWFLAKE_ACCOUNT:-}"
      SNOWFLAKE_WAREHOUSE:  "${SNOWFLAKE_WAREHOUSE:-}"
      SNOWFLAKE_DATABASE:   "${SNOWFLAKE_DATABASE:-}"
      SNOWFLAKE_SCHEMA:     "${SNOWFLAKE_SCHEMA:-}"
      SNOWFLAKE_ROLE:       "${SNOWFLAKE_ROLE:-}"
      DOCS_AT_ROOT: "1"
      FORWARDED_ALLOW_IPS: "*"
    healthcheck:
      test: ["CMD-SHELL", "python - <<'PY'\nimport urllib.request,sys\ntry:\n  urllib.request.urlopen('http://127.0.0.1:8000/healthz', timeout=5)\n  sys.exit(0)\nexcept Exception:\n  sys.exit(1)\nPY"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 5s
    restart: unless-stopped

  ui:
    image: claimsight-ai-ui:latest
    build:
      context: .
      dockerfile: ui/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/workspace
    working_dir: /workspace
    environment:
      API_URL: "http://api:8000"
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: claims
      POSTGRES_PASSWORD: claims
      POSTGRES_DB: claimsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  chroma:
    image: chromadb/chroma
    ports:
      - "8001:8000"           # host:container
    volumes:
      - chroma_data:/chroma/chroma
    restart: unless-stopped

volumes:
  postgres_data:
  chroma_data:
