name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      APP_HOME:  ${{ github.workspace }}
      VECTOR_DIR: ${{ github.workspace }}/.cache/vectorstore
      POLICY_DIR: ${{ github.workspace }}/data/policies

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Prep writable dirs
        run: |
          mkdir -p "$VECTOR_DIR"
          mkdir -p "$POLICY_DIR"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r services/api/requirements.txt
          pip install pytest

      # If you don't have tests yet, Option A keeps CI green without hiding real failures later:
      # - name: Run tests (allow empty suite)
      #   run: pytest -q || (code=$?; [ $code -eq 5 ] && echo "No tests collected; OK for now" || exit $code)

      # If you DO have tests, use this:
      - name: Run tests
        run: pytest -q
