name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      APP_HOME:  ${{ github.workspace }}
      DATA_DIR:  ${{ github.workspace }}/data
      MODELS_DIR: ${{ github.workspace }}/models
      VECTOR_DIR: ${{ github.workspace }}/.cache/vectorstore
      PYTHONPATH: ${{ github.workspace }}        # put repo root on sys.path
      EN_MODEL: en_core_web_sm                    # light spacy model
      PIP_DISABLE_PIP_VERSION_CHECK: "1"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Prepare dirs
        run: |
          mkdir -p "$VECTOR_DIR" "$DATA_DIR" "$MODELS_DIR"

      - name: Install project (editable) + API deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r claimsight_ai/api/requirements.txt

      - name: Sanity import (print sys.path)
        run: |
          python - <<'PY'
          import sys
          print("---- first 10 sys.path entries ----")
          print(*sys.path[:10], sep="\n")
          import importlib
          importlib.import_module("claimsight_ai.integrations")
          print("sanity import OK")
          PY

      - name: Run tests
        run: pytest -vv -p no:cacheprovider
