name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      APP_HOME: ${{ github.workspace }}
      DATA_DIR: ${{ github.workspace }}/data
      MODELS_DIR: ${{ github.workspace }}/models
      VECTOR_DIR: ${{ github.workspace }}/.cache/vectorstore
      PYTHONPATH: ${{ github.workspace }}
      EN_MODEL: en_core_web_sm
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      # ← this makes `torch==2.3.1` resolve reliably in CI
      PIP_EXTRA_INDEX_URL: https://download.pytorch.org/whl/cpu

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: System deps required by wheels (xgboost, etc.)
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libgomp1

      - name: Prepare dirs
        run: |
          mkdir -p "$VECTOR_DIR" "$DATA_DIR" "$MODELS_DIR"

      - name: Install project + API deps + pytest
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          # API reqs (torch resolved via PIP_EXTRA_INDEX_URL)
          pip install -r claimsight_ai/api/requirements.txt
          # Small spaCy model for tests
          python -m spacy download en_core_web_sm || true
          pip install pytest pytest-cov

      - name: Sanity import (print sys.path)
        run: |
          python - <<'PY'
          import sys, importlib
          print("---- first 10 sys.path entries ----")
          print(*sys.path[:10], sep="\n")
          importlib.import_module("claimsight_ai.integrations")
          print("sanity import OK")
          PY

      - name: Run tests
        run: python -m pytest -vv -p no:cacheprovider
