name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      APP_HOME:  ${{ github.workspace }}
      VECTOR_DIR: ${{ github.workspace }}/.cache/vectorstore
      POLICY_DIR: ${{ github.workspace }}/data/policies
      PYTHONPATH: ${{ github.workspace }}
      EN_MODEL: en_core_web_sm

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo structure
        run: |
          sudo apt-get update -y && sudo apt-get install -y tree
          echo "---- repo tree (top 2 levels) ----"
          tree -L 2 || true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Persist PYTHONPATH
        run: echo "PYTHONPATH=${PYTHONPATH}:${GITHUB_WORKSPACE}" >> "$GITHUB_ENV"

      - name: Prep writable dirs
        run: mkdir -p "$VECTOR_DIR" "$POLICY_DIR"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r claimsight_ai/api/requirements.txt
          pip install pytest

      - name: Editable install (project)
        run: pip install -e .

      - name: Sanity import check
        run: |
          python - <<'PY'
          import sys, pprint, importlib
          print("---- first 10 sys.path ----"); pprint.pprint(sys.path[:10])
          importlib.import_module("claimsight_ai.integrations")
          print("✅ import claimsight_ai.integrations OK")
          PY

      - name: Run tests
        env:
          PYTHONWARNINGS: default
        run: pytest -vv
